### ISSUE TITLE
Problems with the launch pgadmin4

### ISSUE THREAD

**Issue by Rus-ai-alt** [EnterpriseDB/edb-installers#154]
File: pgadmin4.log:

2024-09-08 22:18:03,317: ERROR	pgadmin:	Database migration failed
2024-09-08 22:18:03,321: ERROR	pgadmin:	Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\operations\batch.py", line 690, in drop_constraint
    const = self.named_constraints.pop(const.name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'ck_port_range'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\pgadmin\__init__.py", line 386, in upgrade_db
    db_upgrade(app)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\pgadmin\setup\db_upgrade.py", line 25, in db_upgrade
    flask_migrate.upgrade(migration_folder)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\flask_migrate\__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\flask_migrate\__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\command.py", line 406, in upgrade
    script.run_env()
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\script\base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\util\pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\util\pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\pgadmin\setup\..\..\migrations\env.py", line 95, in <module>
    run_migrations_online()
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\pgadmin\setup\..\..\migrations\env.py", line 87, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\runtime\environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\runtime\migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\migrations\versions\7c56ea250085_.py", line 26, in upgrade
    with op.batch_alter_table("server") as batch_op:
  File "contextlib.py", line 144, in __exit__
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\operations\base.py", line 398, in batch_alter_table
    impl.flush()
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\operations\batch.py", line 162, in flush
    fn(*arg, **kw)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\operations\batch.py", line 701, in drop_constraint
    raise ValueError("No such constraint: '%s'" % const.name)
ValueError: No such constraint: 'ck_port_range'

2024-09-08 22:18:03,321: ERROR	pgadmin:	Exception in database migration.
2024-09-08 22:18:03,791: ERROR	pgadmin:	Database migration failed
2024-09-08 22:18:03,793: ERROR	pgadmin:	Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\operations\batch.py", line 690, in drop_constraint
    const = self.named_constraints.pop(const.name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'ck_port_range'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\pgadmin\__init__.py", line 386, in upgrade_db
    db_upgrade(app)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\pgadmin\setup\db_upgrade.py", line 25, in db_upgrade
    flask_migrate.upgrade(migration_folder)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\flask_migrate\__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\flask_migrate\__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\command.py", line 406, in upgrade
    script.run_env()
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\script\base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\util\pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\util\pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\pgadmin\setup\..\..\migrations\env.py", line 95, in <module>
    run_migrations_online()
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\pgadmin\setup\..\..\migrations\env.py", line 87, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\runtime\environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\runtime\migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\migrations\versions\7c56ea250085_.py", line 26, in upgrade
    with op.batch_alter_table("server") as batch_op:
  File "contextlib.py", line 144, in __exit__
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\operations\base.py", line 398, in batch_alter_table
    impl.flush()
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\operations\batch.py", line 162, in flush
    fn(*arg, **kw)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\operations\batch.py", line 701, in drop_constraint
    raise ValueError("No such constraint: '%s'" % const.name)
ValueError: No such constraint: 'ck_port_range'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\operations\batch.py", line 690, in drop_constraint
    const = self.named_constraints.pop(const.name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'ck_port_range'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\pgadmin\__init__.py", line 372, in backup_db_file
    db_upgrade(app)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\pgadmin\setup\db_upgrade.py", line 25, in db_upgrade
    flask_migrate.upgrade(migration_folder)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\flask_migrate\__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\flask_migrate\__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\command.py", line 406, in upgrade
    script.run_env()
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\script\base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\util\pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\util\pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\pgadmin\setup\..\..\migrations\env.py", line 95, in <module>
    run_migrations_online()
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\pgadmin\setup\..\..\migrations\env.py", line 87, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\runtime\environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\runtime\migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\web\migrations\versions\a77a0932a568_.py", line 28, in upgrade
    with op.batch_alter_table("server") as batch_op:
  File "contextlib.py", line 144, in __exit__
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\operations\base.py", line 398, in batch_alter_table
    impl.flush()
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\operations\batch.py", line 162, in flush
    fn(*arg, **kw)
  File "C:\Program Files\PostgreSQL\17\pgAdmin 4\python\Lib\site-packages\alembic\operations\batch.py", line 701, in drop_constraint
    raise ValueError("No such constraint: '%s'" % const.name)
ValueError: No such constraint: 'ck_port_range'

**Comment by Rus-ai-alt** [comment]
My installer doesn’t install all the files because I installed PostgreSQL on another PC, copied the files, and pasted them onto my PC

**Comment by Rus-ai-alt** [comment]
My installer doesn’t install all the files because I installed PostgreSQL on another PC, copied the files, and pasted them onto my PC

**Comment by Rus-ai-alt** [comment]
My installer doesn’t install all the files because I installed PostgreSQL on another PC, copied the files, and pasted them onto my PC
