### ISSUE TITLE
FATAL ERROR

### ISSUE THREAD

**Issue by Simmysola** [EnterpriseDB/edb-installers#159]
Hi there,
When try to open my pgAdmin 4 app, i keep getting a fatal error.

**Comment by Farika2022** [comment]
Total spawn time to start the pgAdmin4 server: 0.048 Sec
2024-09-15 20:32:16,418: ERROR	pgadmin:	Table(s) ['user_mfa'] are missing in the database

Traceback (most recent call last):
  File "C:\Program Files\PostgreSQL\16\pgAdmin 4\web\pgAdmin4.py", line 103, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "C:\Program Files\PostgreSQL\16\pgAdmin 4\web\pgadmin\__init__.py", line 473, in create_app
    run_migration_for_sqlite()
  File "C:\Program Files\PostgreSQL\16\pgAdmin 4\web\pgadmin\__init__.py", line 440, in run_migration_for_sqlite

    backup_db_file()
  File "C:\Program Files\PostgreSQL\16\pgAdmin 4\web\pgadmin\__init__.py", line 368, in backup_db_file
    os.rename(SQLITE_PATH, backup_file_name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 

This is the fatal error I am getting frequently and I cannot resolve it

**Comment by sandeep-edb** [comment]
Could you please try with the latest postgresql installer that was made available? hopefully the issue is resolved

**Comment by Farika2022** [comment]
Thanks
